### ISSUE TITLE
Invalid JSON data

### ISSUE THREAD

**Issue by dfens** [jmatraszek/jmatraszek.github.com#1]
Dear @jmatraszek 

Please check https://github.com/jmatraszek/jmatraszek.github.com/blob/source/resume/resume.json line 35

```json
      {
        "network": "Linkedin",
        "username": "jakub.matraszek",
        "url": "https://github.com/jmatraszek"
      }
```

This is not acceptable. Please resolve this issue as asap as possible

Steps to reproduce:
1) Visit http://matraszek.net/resume/
2) Clink LinkedIn icon
3) Find that link redirects to https://github.com/jmatraszek

**Comment by jmatraszek** [comment]
Fixed, thanks!! :tada:
